# server
server.port=8080

# settings for connecting to the statistics server
stats-server.url=http://stats-server:9090

# Base Data (for Docker)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm-main
spring.datasource.username=ewm_user
spring.datasource.password=ewm_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# logging
logging.level.ru.practicum.ewm=DEBUG
logging.level.org.springframework.web=INFO
logging.level.ru.practicum.stats=DEBUG
logging.level.org.hibernate.SQL=WARN

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

## ????????? ??????????? ???????? ?????? SPRING BOOT
#server.error.whitelabel.enabled=false
#server.error.path=/error
#
## ????????? ????????? ??????
#spring.mvc.throw-exception-if-no-handler-found=false
#spring.web.resources.add-mappings=false
#
## ??????????? ??????
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=never
#server.error.include-exception=true
#
##logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet=INFO
