# server
server.port=9090

# Base Data
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://stats-db:5432/ewm-stats
spring.datasource.username=stats_user
spring.datasource.password=stats_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging
logging.level.ru.practicum.stats=DEBUG
logging.level.org.springframework.web=INFO

# Actuator
management.endpoints.web.exposure.include=health,info,metrics